M48
; DRILL file {KiCad 7.0.10} date Sat 02 Mar 2024 05:11:43 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-02T17:11:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.662Y-2.1503
X3.662Y-3.1345
X5.2368Y-2.1503
X5.2368Y-3.1345
M30
